project_id = "mcldmupqhyhwrfotmyeb"

[functions.admin-login]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.update-admin-password]
verify_jwt = false

[functions.update-portfolio]
verify_jwt = false